services:
  pass:
    image: ortussolutions/commandbox:jre17-3.9.9
    ports:
      - 9001:8080
    volumes:
      - .:/app
  fail:
    image: ortussolutions/commandbox:jre17-3.10.0
    ports:
      - 9002:8080
    volumes:
      - .:/app